### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by voznik** [Tuxkowo/lastfm-loves-deezer#1]
hello!
can you help me understand how to use your app or what the problem is when I try to authorize Deezer?

**Comment by glouvigny** [comment]
Hi,

You probably want to edit ```config.js``` with your Deezer app id (you can get your own by creating a new app on the [Deezer dev site](https://developers.deezer.com/myapps/create)) and the Last.fm api key (get a new one on the [Last.fm website](https://www.last.fm/api/account/create))

By default the Deezer app I created redirects you to localhost.ohai.fr which resolves to 127.0.0.1 and uses the port 80. As port 80 is used, it will require root privileges.

For example, on a Mac you can self host the app by running the following command
```sudo python -m SimpleHTTPServer 80 .```

I hope that will help you.
