### ISSUE TITLE
How to use the script?

### ISSUE THREAD

**Issue by krulik** [Tuxkowo/lastfm-loves-deezer#2]
Hey, I've been Googling for doing this and stumbled upon your script.
It could be great to see some basic example of how to run it.

I'm a long time last.fm user and a recent Deezer user.

**Comment by glouvigny** [comment]
Hi,

This comment may help you https://github.com/glouvigny/lastfm-loves-deezer/issues/1#issuecomment-308522045

**Comment by krulik** [comment]
Thanks, I'll try this out!
